apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop-updated
  name: loop-updated
  namespace: ckad
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo date; done
    image: busybox
    name: loop-updated
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
